### ISSUE TITLE
US 07.01.01 As a borrower, I want to hand over a book I borrowed by scanning the book ISBN code to denote the book as available.

### ISSUE THREAD

**Issue by vhnguyen0707** [CMPUT301F20T33/MobiLibrary#9]
**Rationale:** So other borrowers can know that my book is now available

**Story Points:** 5

**Risk Level:** High

**Comment by happycat33** [comment]
Comment: Wouldn't this apply to the owner? Shouldn't this be letting the owner know the book is available or returned?
